name: Deploy Docs to GitHub Pages with Catalog Builder Tool

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'docs/**'
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Build Catalog Builder tool
    - name: Build Catalog Builder Tool
      run: dotnet build src/TableCloth.CatalogBuilder/TableCloth.CatalogBuilder.csproj --configuration Release

    # Setup Cloudflare Zero Trust
    - name: Establish Cloudflare Zero Trust
      uses: Boostport/setup-cloudflare-warp@v1
      with:
        organization: rkttu
        auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
        auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}

    # Run Catalog Builder tool
    - name: Run Catalog Builder Tool
      run: dotnet run --project src/TableCloth.CatalogBuilder/TableCloth.CatalogBuilder.csproj --configuration Release -- ./docs/ ./outputs/

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./outputs
        publish_branch: gh-pages
